---
- name: install sysctl (apt)
  become: yes
  apt:
    name: procps
    state: present
  when: "ansible_pkg_mgr == 'apt'"

- name: install systemd (dnf)
  become: yes
  package:
    name: systemd
    state: present
  when: "ansible_pkg_mgr == 'dnf'"

- name: set max_queued_events
  become: yes
  sysctl:
    name: fs.inotify.max_queued_events
    value: '{{ inotify_max_queued_events | string }}'
    state: present
    reload: '{{ inotify_reload }}'
    sysctl_file: '{{ inotify_sysctl_file }}'
  when: "inotify_max_queued_events is defined and inotify_max_queued_events not in (None, '', omit)"

- name: set max_user_instances
  become: yes
  sysctl:
    name: fs.inotify.max_user_instances
    value: '{{ inotify_max_user_instances | string }}'
    state: present
    reload: '{{ inotify_reload }}'
    sysctl_file: '{{ inotify_sysctl_file }}'
  when: "inotify_max_user_instances is defined and inotify_max_user_instances not in (None, '', omit)"

- name: set max_user_watches
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: '{{ inotify_max_user_watches | string }}'
    state: present
    reload: '{{ inotify_reload }}'
    sysctl_file: '{{ inotify_sysctl_file }}'
  when: "inotify_max_user_watches is defined and inotify_max_user_watches not in (None, '', omit)"
