---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: "ansible_pkg_mgr == 'apt'"

  roles:
    - role: ansible-role-inotify
      inotify_sysctl_file: /etc/sysctl.d/10-ansible-inotify.conf
      inotify_reload: no
    - role: ansible-role-inotify
      inotify_max_queued_events: 16384
      inotify_max_user_instances: 128
      inotify_max_user_watches: 524288
      inotify_reload: no
